export const skipData = [
  {
    id: 1,
    url: "https://yozbrydxdlcxghkphhtq.supabase.co/storage/v1/object/public/skips/skip-sizes/4-yarder-skip.jpg",
    title: "4 Yard Skip",
    subtitle: "14 day hire period",
    value: "211",
    cardBadge: "4 Yards",
  },
  {
    id: 2,
    url: "https://yozbrydxdlcxghkphhtq.supabase.co/storage/v1/object/public/skips/skip-sizes/4-yarder-skip.jpg",
    title: "4 Yard Skip",
    subtitle: "14 day hire period",
    value: "211",
    cardBadge: "4 Yards",
  },

  {
    id: 3,
    url: "https://yozbrydxdlcxghkphhtq.supabase.co/storage/v1/object/public/skips/skip-sizes/4-yarder-skip.jpg",
    title: "4 Yard Skip",
    subtitle: "14 day hire period",
    value: "211",
    cardBadge: "4 Yards",
  },
  {
    id: 4,
    url: "https://yozbrydxdlcxghkphhtq.supabase.co/storage/v1/object/public/skips/skip-sizes/4-yarder-skip.jpg",
    title: "4 Yard Skip",
    subtitle: "14 day hire period",
    value: "211",
    cardBadge: "4 Yards",
  },
  {
    id: 5,
    url: "https://yozbrydxdlcxghkphhtq.supabase.co/storage/v1/object/public/skips/skip-sizes/4-yarder-skip.jpg",
    title: "4 Yard Skip",
    subtitle: "14 day hire period",
    value: "211",
    cardBadge: "4 Yards",
  },
  {
    id: 6,
    url: "https://yozbrydxdlcxghkphhtq.supabase.co/storage/v1/object/public/skips/skip-sizes/4-yarder-skip.jpg",
    title: "4 Yard Skip",
    subtitle: "14 day hire period",
    value: "211",
    cardBadge: "4 Yards",
  },
  {
    id: 7,
    url: "https://yozbrydxdlcxghkphhtq.supabase.co/storage/v1/object/public/skips/skip-sizes/4-yarder-skip.jpg",
    title: "4 Yard Skip",
    subtitle: "14 day hire period",
    value: "211",
    cardBadge: "4 Yards",
  },
];
