export const skipData = [
  {
    id: 1,
    url: "https://yozbrydxdlcxghkphhtq.supabase.co/storage/v1/object/public/skips/skip-sizes/4-yarder-skip.jpg",
    subtitle: "14 day hire period",
    value: "211",
    yards: "4",
    isAllowedRoad: true,
  },
  {
    id: 2,
    url: "https://yozbrydxdlcxghkphhtq.supabase.co/storage/v1/object/public/skips/skip-sizes/5-yarder-skip.jpg",
    subtitle: "14 day hire period",
    value: "241",
    yards: "5",
    isAllowedRoad: true,
  },

  {
    id: 3,
    url: "https://yozbrydxdlcxghkphhtq.supabase.co/storage/v1/object/public/skips/skip-sizes/5-yarder-skip.jpg",
    subtitle: "14 day hire period",
    value: "264",
    yards: "6",
    isAllowedRoad: true,
  },
  {
    id: 4,
    url: "https://yozbrydxdlcxghkphhtq.supabase.co/storage/v1/object/public/skips/skip-sizes/5-yarder-skip.jpg",
    subtitle: "14 day hire period",
    value: "295",
    yards: "8",
    isAllowedRoad: true,
  },
  {
    id: 5,
    url: "https://yozbrydxdlcxghkphhtq.supabase.co/storage/v1/object/public/skips/skip-sizes/5-yarder-skip.jpg",
    subtitle: "14 day hire period",
    value: "356",
    yards: "10",
    isAllowedRoad: false,
  },
  {
    id: 6,
    url: "https://yozbrydxdlcxghkphhtq.supabase.co/storage/v1/object/public/skips/skip-sizes/5-yarder-skip.jpg",
    subtitle: "14 day hire period",
    value: "390",
    yards: "12",
    isAllowedRoad: false,
  },
  {
    id: 7,
    url: "https://yozbrydxdlcxghkphhtq.supabase.co/storage/v1/object/public/skips/skip-sizes/5-yarder-skip.jpg",
    subtitle: "14 day hire period",
    value: "434",
    yards: "14",
    isAllowedRoad: false,
  },
  {
    id: 8,
    url: "https://yozbrydxdlcxghkphhtq.supabase.co/storage/v1/object/public/skips/skip-sizes/16-yarder-skip.jpg",
    subtitle: "7 day hire period",
    value: "510",
    yards: "16",
    isAllowedRoad: false,
  },
  {
    id: 9,
    url: "https://yozbrydxdlcxghkphhtq.supabase.co/storage/v1/object/public/skips/skip-sizes/20-yarder-skip.jpg",
    subtitle: "14 day hire period",
    value: "802",
    yards: "20",
    isAllowedRoad: false,
  },
  {
    id: 10,
    url: "https://yozbrydxdlcxghkphhtq.supabase.co/storage/v1/object/public/skips/skip-sizes/20-yarder-skip.jpg",
    subtitle: "14 day hire period",
    value: "877",
    yards: "40",
    isAllowedRoad: false,
  },
];
