export const skipData = [
  {
    id: 1,
    url: "https://yozbrydxdlcxghkphhtq.supabase.co/storage/v1/object/public/skips/skip-sizes/4-yarder-skip.jpg",
    title: "4 Yard Skip",
    subtitle: "14 day hire period",
    value: "211",
    cardBadge: "4 Yards",
    isAllowedRoad: true,
  },
  {
    id: 2,
    url: "https://yozbrydxdlcxghkphhtq.supabase.co/storage/v1/object/public/skips/skip-sizes/5-yarder-skip.jpg",
    title: "5 Yard Skip",
    subtitle: "14 day hire period",
    value: "211",
    cardBadge: "4 Yards",
    isAllowedRoad: true,
  },

  {
    id: 3,
    url: "https://yozbrydxdlcxghkphhtq.supabase.co/storage/v1/object/public/skips/skip-sizes/5-yarder-skip.jpg",
    title: "6 Yard Skip",
    subtitle: "14 day hire period",
    value: "211",
    cardBadge: "4 Yards",
    isAllowedRoad: true,
  },
  {
    id: 4,
    url: "https://yozbrydxdlcxghkphhtq.supabase.co/storage/v1/object/public/skips/skip-sizes/5-yarder-skip.jpg",
    title: "8 Yard Skip",
    subtitle: "14 day hire period",
    value: "211",
    cardBadge: "4 Yards",
    isAllowedRoad: true,
  },
  {
    id: 5,
    url: "https://yozbrydxdlcxghkphhtq.supabase.co/storage/v1/object/public/skips/skip-sizes/5-yarder-skip.jpg",
    title: "10 Yard Skip",
    subtitle: "14 day hire period",
    value: "211",
    cardBadge: "4 Yards",
    isAllowedRoad: false,
  },
  {
    id: 6,
    url: "https://yozbrydxdlcxghkphhtq.supabase.co/storage/v1/object/public/skips/skip-sizes/5-yarder-skip.jpg",
    title: "12 Yard Skip",
    subtitle: "14 day hire period",
    value: "211",
    cardBadge: "4 Yards",
    isAllowedRoad: false,
  },
  {
    id: 7,
    url: "https://yozbrydxdlcxghkphhtq.supabase.co/storage/v1/object/public/skips/skip-sizes/5-yarder-skip.jpg",
    title: "14 Yard Skip",
    subtitle: "14 day hire period",
    value: "211",
    cardBadge: "4 Yards",
    isAllowedRoad: false,
  },
  {
    id: 8,
    url: "https://yozbrydxdlcxghkphhtq.supabase.co/storage/v1/object/public/skips/skip-sizes/16-yarder-skip.jpg",
    title: "14 Yard Skip",
    subtitle: "16 day hire period",
    value: "211",
    cardBadge: "4 Yards",
    isAllowedRoad: false,
  },
  {
    id: 9,
    url: "https://yozbrydxdlcxghkphhtq.supabase.co/storage/v1/object/public/skips/skip-sizes/20-yarder-skip.jpg",
    title: "14 Yard Skip",
    subtitle: "20 day hire period",
    value: "211",
    cardBadge: "4 Yards",
    isAllowedRoad: false,
  },
  {
    id: 9,
    url: "https://yozbrydxdlcxghkphhtq.supabase.co/storage/v1/object/public/skips/skip-sizes/20-yarder-skip.jpg",
    title: "40 Yard Skip",
    subtitle: "20 day hire period",
    value: "211",
    cardBadge: "4 Yards",
    isAllowedRoad: false,
  },
];
